version: '3.6'

services:
  mongo:
    image: mongo:4.0

  director:
    image: kenaz201/sorry-cypress:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/cos.driver'
      COS_ENDPOINT: 'https://s3.us-south.cloud-object-storage.appdomain.cloud'
      COS_READ_ENDPOINT: 'https://nightwatch-function.s3.us-south.cloud-object-storage.appdomain.cloud'
      COS_APIKEY: 'R4JM95xxW-P4AZZbttTbOMC31TFn7XeNSNvYqLIchbJp"'
      COS_REGION: 'us-south'
      COS_BUCKET: 'nightwatch-function'
      COS_SERVICEINSTANCE: 'crn:v1:bluemix:public:cloud-object-storage:global:a/dbf2281ba8634a0caf0dece4cefa7c08:f581ffdb-4ebf-49ec-8c78-d79075073d6f::'
    ports:
      - 1234:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api
