version: '3.6'

services:
  mongo:
    image: mongo:4.0

  director:
    image: juanjosepb/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/cos.driver'
      COS_ENDPOINT: ''
      COS_APIKEY: ''
      COS_REGION: ''
      COS_BUCKET: ''
      COS_SERVICEINSTANCE: ''
    ports:
      - 1234:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api
