version: 2.1

aliases:
  - &checkout # Custom checkout because circle doesnt use -depth 1 and our repo is 200Mo, went from 45s to 3s checkout
    name: checkout
    command: |
      git clone -n ${CIRCLE_REPOSITORY_URL} ~/project/
      cd ~/project/
      git checkout ${CIRCLE_SHA1}

jobs:
  build-director-and-push:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    environment:
      DOCKER_BUILDKIT: '1'
    working_directory: ~/project
    steps:
      - run: *checkout
      - run:
          name: build docker image
          no_output_timeout: 1h
          command: |
            FULL_TAG=${CIRCLE_SHA1}
            docker login ${ACR_HOST} -u ${ACR_PUSH_USER} -p ${ACR_PUSH_PASSWORD}

            # Build and push DIRECTOR
            cd ~/project/packages/director/
            if ! docker image pull ${ACR_HOST}/padoa-tools/sorry-cypress-director:$FULL_TAG ; then
              docker build --progress plain -t ${ACR_HOST}/padoa-tools/sorry-cypress-director:$FULL_TAG .
              docker push ${ACR_HOST}/padoa-tools/sorry-cypress-director:$FULL_TAG
            fi

  build-api-and-push:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    environment:
      DOCKER_BUILDKIT: '1'
    working_directory: ~/project
    steps:
      - run: *checkout
      - run:
          name: build docker image
          no_output_timeout: 1h
          command: |
            FULL_TAG=${CIRCLE_SHA1}
            docker login ${ACR_HOST} -u ${ACR_PUSH_USER} -p ${ACR_PUSH_PASSWORD}

            # Build and push API
            cd ~/project/packages/api/
            if ! docker image pull ${ACR_HOST}/padoa-tools/sorry-cypress-api:$FULL_TAG ; then
              docker build --progress plain -t ${ACR_HOST}/padoa-tools/sorry-cypress-api:$FULL_TAG .
              docker push ${ACR_HOST}/padoa-tools/sorry-cypress-api:$FULL_TAG
            fi

  build-dashboard-and-push:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    environment:
      DOCKER_BUILDKIT: '1'
    working_directory: ~/project
    steps:
      - run: *checkout
      - run:
          name: build docker image
          no_output_timeout: 1h
          command: |
            FULL_TAG=${CIRCLE_SHA1}
            docker login ${ACR_HOST} -u ${ACR_PUSH_USER} -p ${ACR_PUSH_PASSWORD}

            # Build and push DASHBOARD
            cd ~/project/packages/dashboard/
            if ! docker image pull ${ACR_HOST}/padoa-tools/sorry-cypress-dashboard:$FULL_TAG ; then
              docker build --progress plain -t ${ACR_HOST}/padoa-tools/sorry-cypress-dashboard:$FULL_TAG .
              docker push ${ACR_HOST}/padoa-tools/sorry-cypress-dashboard:$FULL_TAG
            fi
workflows:
  build-and-push:
    jobs:
      - build-director-and-push:
          context:
            - REGISTRY
      - build-api-and-push:
          context:
            - REGISTRY
      - build-dashboard-and-push:
          context:
            - REGISTRY
